source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftSample' do

  use_frameworks!
  platform :ios, '9.0'

  pod 'Smart-Display-SDK', '~> 7.8.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
